minor updates

diff --git a/bin/cakedev b/bin/cakedev
--- a/bin/cakedev
+++ b/bin/cakedev
@@ -2,7 +2,7 @@
 
 PWD=$(pwd)
 
-trap "{ cd $PWD ; unset PHPUNIT_ARGS ; exit 255; }" SIGINT SIGTERM EXIT
+trap "{ cd $PWD ; exit 255; }" SIGINT SIGTERM EXIT
 
 TARGET=$1
 WD=$2
@@ -22,92 +22,23 @@ if [[ -z $PHINGFILE ]]; then
   echo "PHINGFILE not defined. Fallback to $PHINGFILE"
 fi
 
-cd ${WD} #|| echo "Failed to enter working directory" && exit 1
+cd ${WD} || { echo "Failed to enter working directory"; exit 1; }
 
 case "${TARGET}" in
-  "list")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} -list
-  ;;
-
-  # Helper commands
-  "info")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "clean")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "prepare")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-
-  # Tool commands
-  "phpunit")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpunit-no-coverage")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpdox")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "pdepend")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "lint")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phploc")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phploc-ci")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpmd")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpmd-ci")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpcs")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpcs-ci")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpcbf")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpcpd")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpcpd-ci")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpstan")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "phpstan-ci")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-
-  # Wrapper commands
-  "full-build")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "quick-build")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "quick-test")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  "static-analysis")
-    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
-  ;;
-  *)
+  "help"|"")
     echo "Usage: $0 [TARGET] [WORKING-DIR]"
     echo "Available phing targets:"
     $PHING -Dbasedir=${WD} -f ${PHINGFILE} -list
     exit 1
   ;;
+
+  "list")
+    $PHING -Dbasedir=${WD} -f ${PHINGFILE} -list
+  ;;
+
+  *)
+    $PHING -Dbasedir=${WD} -f ${PHINGFILE} ${TARGET}
+  ;;
 esac
 
+exit 0
